# Production Configuration

# Server
server.port=8443

# HTTP2
server.http2.enabled=true

# HTTPS:
server.ssl.key-store=file:${SSL_KEYSTORE_PATH}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=${SSL_KEYSTORE_TYPE}
server.ssl.key-alias=BikePartsFinder

# llama-server Konfiguration
llama.server.lifecycle.auto-start=true
llama.server.lifecycle.auto-shutdown=true
llama.server.model=/home/ellen/bikepartsSoftware/ki_models/qwen2.5-3b-instruct-q3_k_m.gguf
#llama.server.model=qwen2.5-3b-instruct-q3_k_m.gguf
llama.server.exe=/home/ellen/bikepartsSoftware/llama.cpp-server/llama-b8308/llama-server
llama.server.serverBaseUrl=http://localhost

# Temporaer: H2 In-Memory Datenbank; spaeter MySQL/PostgreSQL verwenden!
spring.datasource.url=jdbc:h2:mem:mydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

# SQL-Initialisierung mit Testdaten
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-ellen.sql,classpath:data-cache-bikeComponentsSearch-Shimano-Kette-SLX.sql,classpath:data-cache-shopInfo.sql

# Thymeleaf
spring.thymeleaf.cache=true

# Logging
logging.level.root=WARN
logging.level.com.example=INFO
logging.level.org.springframework=WARN
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

