# Spring Boot Configuration 

# Application Name
spring.application.name=bikeparts-app

# JWT Token Configuration
# JWT_SECRET_KEY aus Sicherheitsgruenden in application-local.properties ausgelagert.
# siehe Vorlage application-local.properties.example
# Notiz: IntelliJ sagt: unused property. Aber sie wird als @Value-Felde verwendet und funktioniert korrekt!
app.jwt.secret=${JWT_SECRET_KEY:PleaseSet_JWT_SECRET_KEY_in_application-local.properties_file}
app.jwt.expiration=86400000

# start application in dev. Better: mvn spring-boot:run -Dspring-boot.run.profiles=dev
#spring.profiles.active=dev
spring.profiles.active=h2

# Server
server.port=8080
# Session-Persistenz deaktivieren (verhindert ClassCastException beim Devtools-Restart)
server.servlet.session.persistent=false

# llama-server Konfiguration
llama.server.lifecycle.auto-start=true
llama.server.lifecycle.auto-shutdown=true
llama.server.model=C:/dev/IBB/Referenzprojekt/ki_models/qwen2.5-1.5b-instruct-q4_k_m.gguf
#llama.server.model=qwen2.5-3b-instruct-q3_k_m.gguf
llama.server.exe=C:/dev/IBB/Referenzprojekt/llama.cpp-server/llama-b8308-bin-win-cpu-x64/llama-server.exe
llama.server.serverBaseUrl=http://localhost
#llama.server.serverBaseUrl=http://127.0.0.1
llama.server.port=8099
llama.server.threads=4
llama.server.context=2048
llama.server.timeout=100


# Modell
llama.model.path=C:/dev/IBB/Referenzprojekt/ki_models/qwen2.5-1.5b-instruct-q4_k_m.gguf


#
## Thymeleaf
#spring.thymeleaf.cache=false
##spring.thymeleaf.prefix=classpath:/templates/
##spring.thymeleaf.suffix=.html
#
## Logging
logging.level.root=WARN
logging.level.com.bikeparts=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
#
## Logging in Datei
## logging.file.name=/var/log/bikeparts-app/application.log
#logging.file.name=logs/application.log
#logging.file.max-size=5MB
#logging.file.max-history=30
#
## Person App-Konfiguration
#app.name=Persons Management System
#app.version=1.0.0
#app.max-persons=200
#app.features.email-enabled=true
#
## Externe API-Keys (Beispiel) -> export API_KEY=dein-geheimer-key
#app.api.key=${API_KEY}
#app.api.secret=${API_SECRET}
## Admin Credentials
#app.admin.username=${ADMIN_USERNAME}
#app.admin.password=${ADMIN_PASSWORD}
