
# llama-server Konfiguration
llama.server.lifecycle.auto-start=false
llama.server.lifecycle.auto-shutdown=true

# Thymeleaf
spring.thymeleaf.cache=false

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:mydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (zum Debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
# create first the database, then call sql script data.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging
#logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# SQL-Initialisierung
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-ellen.sql,classpath:data-cache-bikeComponentsSearch-Shimano-Kette-SLX.sql,classpath:data-cache-shopInfo-bikeComponents.sql

# Cache
spring.cache.cache-names=bikeComponentsSearch
spring.cache.caffeine.spec=expireAfterWrite=14d