# Production Configuration

# Server
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=true

# Logging
logging.level.root=WARN
logging.level.com.example=INFO
logging.level.org.springframework=WARN

