# Development Configuration

# Server
server.port=8080
server.servlet.context-path=/

# Thymeleaf
spring.thymeleaf.cache=false

# Logging
logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=INFO
logging.level.org.hibernate.SQL=DEBUG

# In Dev nutzen wir Dummy-Werte
app.api.key=${API_KEY:dev-dummy-key}
