# Production Configuration

# Server
server.port=8080

# llama-server Konfiguration
llama.server.lifecycle.auto-start=true
llama.server.lifecycle.auto-shutdown=true
llama.server.model=/home/ellen/bikepartsSoftware/ki_models/qwen2.5-3b-instruct-q3_k_m.gguf
#llama.server.model=qwen2.5-3b-instruct-q3_k_m.gguf
llama.server.exe=/home/ellen/bikepartsSoftware/llama.cpp-server/llama-b8308/llama-server
llama.server.serverBaseUrl=http://localhost

# Thymeleaf
spring.thymeleaf.cache=true

# Logging
logging.level.root=WARN
logging.level.com.example=INFO
logging.level.org.springframework=WARN
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

