http_port 3128

# Cache-Verzeichnis (1 GB)
cache_dir ufs /var/spool/squid 1000 16 256
maximum_object_size 10 MB

# max-age: 1440 Minuten = 24 Stunden
# Format: refresh_pattern <regex> <min> <percent> <max>
# -------------------------------------------------------
# bike-components.de
# -------------------------------------------------------

# 4 Stunden = 240
# 24 Stunden = 1440
# Suchergebnisse: 24 Stunden cachen
refresh_pattern -i bike-components\.de/de/s/\?keywords=   60  50%  1440  override-expire
# Versandkosten: 24 Stunden cachen (ändern sich selten)
refresh_pattern -i bike-components\.de/de/service/versand/   60  50%  1440  override-expire

# -------------------------------------------------------
# bike-discount.de
# -------------------------------------------------------
# Suchergebnisse: 24 Stunden cachen
refresh_pattern -i bike-discount\.de/de/search\?search=   60  50%  1440  override-expire
# Versandkosten: 24 Stunden cachen
refresh_pattern -i bike-discount\.de/de/shippingcosts   60  50%  1440  override-expire

# -------------------------------------------------------
# Alles andere: Standard
# -------------------------------------------------------
refresh_pattern .   0  20%  4320

# Zugriff erlauben
http_access allow all
